// mod day01;
// mod day02;
// mod day03;
mod day04;
// mod day05;
// mod day06;
// mod day07;
// mod day08;
// mod day09;
// mod day10;
// mod day11;
// mod day12;
// mod day13;
// mod day14;
// mod day15;
// mod day16;
// mod day17;
// mod day18;
// mod day19;
// mod day20;
// mod day21;
// mod day22;
// mod day23;
// mod day24;
// mod day25;

fn main() {
  // dbg!(day01::compute(include_str!("../input/day01.txt")));
  // dbg!(day02::compute(include_str!("../input/day02.txt")));
  // dbg!(day03::compute(include_str!("../input/day03.txt")));
  dbg!(day04::compute(include_str!("../input/day04.txt")));
  // dbg!(day05::compute(include_str!("../input/day05.txt")));
  // dbg!(day06::compute(include_str!("../input/day06.txt")));
  // dbg!(day07::compute(include_str!("../input/day07.txt")));
  // dbg!(day08::compute(include_str!("../input/day08.txt")));
  // dbg!(day09::compute(include_str!("../input/day09.txt")));
  // dbg!(day10::compute(include_str!("../input/day10.txt")));
  // dbg!(day11::compute(include_str!("../input/day11.txt")));
  // dbg!(day12::compute(include_str!("../input/day12.txt")));
  // dbg!(day13::compute(include_str!("../input/day13.txt")));
  // dbg!(day14::compute(include_str!("../input/day14.txt")));
  // dbg!(day15::compute(include_str!("../input/day15.txt")));
  // dbg!(day16::compute(include_str!("../input/day16.txt")));
  // dbg!(day17::compute(include_str!("../input/day17.txt")));
  // dbg!(day18::compute(include_str!("../input/day18.txt")));
  // dbg!(day19::compute(include_str!("../input/day19.txt")));
  // dbg!(day20::compute(include_str!("../input/day20.txt")));
  // dbg!(day21::compute(include_str!("../input/day21.txt")));
  // dbg!(day22::compute(include_str!("../input/day22.txt")));
  // dbg!(day23::compute(include_str!("../input/day23.txt")));
  // dbg!(day24::compute(include_str!("../input/day24.txt")));
  // dbg!(day25::compute(include_str!("../input/day25.txt")));
}
